version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:10.15-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node_modules-{{ .Branch }}
            - node_modules-master
            - node_modules-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Yarn Version
          command: yarn --version

      - run:
          name: Install
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save node_modules cache
          key: node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test

      - run:
          name: Build
          command: yarn build

      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
